loadModule('prison/lib/vendor/jquery.js');
loadModule('prison/lib/vendor/jquery-ui.js');
loadModule('prison/lib/utils.js');
loadModule('prison/lib/sampa.js');
loadModule('prison/lib/edit.js');
loadModule('prison/lib/highlight.js');
loadModule('prison/lib/multiple.js');
loadModule('prison/lib/vendor/jquery-svgpan.js');
loadModule('prison/lib/vendor/treelib.js');
loadModule('prison/lib/newick.js');
loadModule('prison/lib/concepticon.js');
loadModule('prison/lib/vendor/FileSaver.js');
loadModule('prison/lib/vendor/jquery.editable.min.js');
loadModule('prison/lib/jsonp.js');

loadStyle('prison/style/treelib.css');
loadStyle('prison/style/jquery-ui.css');
loadStyle('prison/style/dighl.css');
loadStyle('prison/style/wordlist.css');
